import { it, expect, describe } from "vitest";
import * as fs from "fs";
import { join as pathJoin } from "path";
import {
    getReactDsfrImportedModuleIds,
    resolveModuleIdToDsfrComponents
} from "../../../../src/bin/only-include-css-of-used-components";

/**
 * The component CSS optimizer maps every imported react-sds module to the DSFR CSS
 * components it renders. A module that is in neither REACT_DSFR_MODULE_TO_DSFR_COMPONENTS
 * nor NON_COMPONENT_MODULE_IDS makes resolveModuleIdToDsfrComponents() return undefined,
 * which trips the include-everything fail-safe: the script warns and exits 0, so a
 * consumer importing a component added after the map was written silently stops getting
 * any CSS trimmed at all. Nothing else in the test suite notices.
 *
 * This test is the guard: adding a component to `src/` without adding it to one of the
 * two maps fails here, naming the module.
 *
 * On what counts as a public module: `package.json` `exports` is generated by
 * `scripts/build/list-exports.ts` (run by `pnpm build`) from the files `tsc -p src` emits
 * into `dist/`, so the published subpaths are exactly the emitted modules. The enumeration
 * below therefore replays that emission: the entries of `src/`, minus what `src/tsconfig.json`
 * excludes (read from the file, not hardcoded, so a future exclude stays in sync) and minus
 * the files tsc does not emit a module for.
 */
describe("REACT_DSFR_MODULE_TO_DSFR_COMPONENTS exhaustiveness", () => {
    const projectRootDirPath = process.cwd();
    const srcDirPath = pathJoin(projectRootDirPath, "src");

    /**
     * Top level names excluded from the `tsc -p src` emission, e.g. "bin".
     * Only the first path segment is kept, so a pattern is still understood if it is ever
     * widened to a glob ("./bin" and "./bin/**" both yield "bin").
     */
    const getSrcTsconfigExcludedNames = (): Set<string> => {
        const { exclude }: { exclude?: string[] } = JSON.parse(
            fs.readFileSync(pathJoin(srcDirPath, "tsconfig.json")).toString("utf8")
        );

        return new Set((exclude ?? []).map(pattern => pattern.replace(/^\.\//, "").split("/")[0]));
    };

    const isModuleSourceFileName = (fileName: string): boolean =>
        /\.tsx?$/.test(fileName) && !fileName.endsWith(".d.ts");

    const removeExtension = (fileName: string): string => fileName.replace(/\.tsx?$/, "");

    const hasAnIndex = (dirPath: string): boolean =>
        fs.readdirSync(dirPath).some(childName => /^index\.tsx?$/.test(childName));

    /**
     * The `@skygenesisenterprise/react-sds/<subpath>` a consumer can import, one per module the
     * script has to resolve. Not every importable path: `tools/powerhooks/useConst` is
     * importable too, but yields the same module id as `tools/cx`, so listing the
     * shallowest path per module is enough and keeps failure messages readable.
     *
     * A directory with an index is importable as is. One without (Chart, blocks, shared,
     * tools...) is only reachable deeper, so its children are listed instead, which is what
     * produces the two segment "blocks/PasswordInput". A child directory is importable in
     * turn only if it has an index of its own: `tools/StatefulObservable` has one,
     * `tools/powerhooks` does not.
     */
    const getPublicSubpaths = (): string[] => {
        const excludedNames = getSrcTsconfigExcludedNames();

        const subpaths: string[] = [];

        for (const dirent of fs.readdirSync(srcDirPath, { "withFileTypes": true })) {
            if (excludedNames.has(dirent.name)) {
                continue;
            }

            if (!dirent.isDirectory()) {
                if (isModuleSourceFileName(dirent.name)) {
                    // A top-level index (src/index.ts, the package main entry) is not an
                    // importable subpath: consumers reach it through the bare package name,
                    // which the root-import handling covers (ROOT_IMPORT_MODULE_ID).
                    if (dirent.name === "index.ts" || dirent.name === "index.tsx") {
                        continue;
                    }

                    subpaths.push(removeExtension(dirent.name));
                }
                continue;
            }

            const dirPath = pathJoin(srcDirPath, dirent.name);

            if (hasAnIndex(dirPath)) {
                subpaths.push(dirent.name);
                continue;
            }

            for (const childDirent of fs.readdirSync(dirPath, { "withFileTypes": true })) {
                // Files are kept whatever their extension: src/assets holds only .svg and
                // .css, and skipping those would drop the "assets" module id altogether,
                // silently leaving it unchecked.
                if (childDirent.isDirectory() && !hasAnIndex(pathJoin(dirPath, childDirent.name))) {
                    continue;
                }

                subpaths.push(`${dirent.name}/${removeExtension(childDirent.name)}`);
            }
        }

        return subpaths;
    };

    /**
     * Goes through the production extraction rather than reimplementing it, so the module
     * ids asserted here are the ones the script will actually resolve at run time.
     */
    const getModuleIdBySubpath = (): Map<string, string[]> =>
        new Map(
            getPublicSubpaths().map(subpath => [
                subpath,
                getReactDsfrImportedModuleIds({
                    "rawFileContent": `import "@skygenesisenterprise/react-sds/${subpath}";`
                })
            ])
        );

    it("covers every module publicly exposed by src/", () => {
        // One list, one assertion: every problem found in this run is reported at once.
        // Asserting inside the loop, or once per category, would abort on the first
        // offender and hide the rest, turning a single fix-and-rerun cycle into several.
        const problems: string[] = [];

        for (const [subpath, moduleIds] of getModuleIdBySubpath()) {
            // A public subpath must yield exactly one module id, otherwise the extraction
            // dropped it and its coverage would go unchecked, vacuously passing.
            if (moduleIds.length !== 1) {
                problems.push(
                    `src/${subpath}: extraction yielded ${moduleIds.length} module ids, expected 1`
                );
                continue;
            }

            const [moduleId] = moduleIds;

            if (resolveModuleIdToDsfrComponents({ moduleId }) === undefined) {
                problems.push(`${moduleId} (from src/${subpath}): resolves to undefined`);
            }
        }

        expect(
            problems,
            [
                `The component CSS optimizer would fall back to including every DSFR`,
                `component because of:`,
                ...problems.map(entry => `  - ${entry}`),
                ``,
                `Add each unresolved module to REACT_DSFR_MODULE_TO_DSFR_COMPONENTS (with the`,
                `DSFR components its markup renders, transitive dependencies included) or to`,
                `NON_COMPONENT_MODULE_IDS if it renders no DSFR markup, in`,
                `src/bin/only-include-css-of-used-components.ts.`
            ].join("\n")
        ).toStrictEqual([]);
    });

    it("enumerates the public modules from the real src/ layout", () => {
        // Guards the enumeration itself: were getPublicSubpaths() to return nothing, or to
        // quietly stop covering a module, the assertion above would pass on what it no
        // longer looks at. Narrowing the enumeration has to fail here, not go unnoticed.
        const subpaths = getPublicSubpaths();

        expect(subpaths.length).toBeGreaterThan(40);

        for (const expected of ["Header", "Highlight", "blocks/PasswordInput", "i18n"]) {
            expect(subpaths).toContain(expected);
        }

        // One representative per shape: a component directory with an index, a flat file,
        // index-less directories reached through a child, and a directory whose children
        // are not TypeScript at all (src/assets holds only .svg and .css).
        const moduleIds = new Set(Array.from(getModuleIdBySubpath().values()).flat());

        for (const expected of ["Header", "Alert", "Chart", "tools", "shared", "assets"]) {
            expect(moduleIds).toContain(expected);
        }

        // `src/tsconfig.json` excludes `./bin`: the CLI is not a public import subpath.
        expect(subpaths.some(subpath => subpath.startsWith("bin"))).toBe(false);
    });

    it("public subpaths are reachable through the package.json exports map", () => {
        // The exports map is generated by scripts/build/list-exports.ts from the files
        // actually emitted in `dist/`. Every enumerated src/ subpath must therefore have an
        // explicit export of its own — a `./*` wildcard would silently let the map drift
        // from the emitted files (and cannot resolve directories / extension-less targets
        // anyway). The dedicated packaging test (test/runtime/package/package-exports.test.ts)
        // regenerates the map and verifies every target exists; here we only guard that the
        // enumeration contract is covered and that the isolation of the Discord entry holds.
        const packageJsonParsed = JSON.parse(
            fs.readFileSync(pathJoin(projectRootDirPath, "package.json")).toString("utf8")
        );

        const exports = packageJsonParsed["exports"] as Record<string, unknown>;

        expect(exports).toBeDefined();

        // No wildcard: the map is an explicit, exhaustive list.
        expect(exports["./*"]).toBeUndefined();

        for (const subpath of getPublicSubpaths()) {
            expect(
                exports[`./${subpath}`],
                `src/${subpath} must have an explicit package.json export`
            ).toBeDefined();
        }

        // The Discord integration is only reachable through its dedicated subpaths.
        expect(exports["./discord"]).toBeDefined();
        expect(exports["./discord/server"]).toBeDefined();

        // CSS / runtime entries stay importable.
        expect(exports["./main.css"]).toBeDefined();
        expect(exports["./early-color-scheme.js"]).toBeDefined();
        expect(exports["./package.json"]).toBeDefined();

        // Deep subpaths of the reported consumer errors are officially public.
        for (const subpath of [
            "./Header",
            "./SkipLinks",
            "./MainNavigation",
            "./MainNavigation/MegaMenu",
            "./Display"
        ]) {
            expect(
                exports[subpath],
                `${subpath} must have an explicit package.json export`
            ).toBeDefined();
        }
    });
});
